version: "3.1"
services:
    mailhog:
      image: mailhog/mailhog:latest
      container_name: resume-aranda-pablo-mailhog
      ports:
        - "8081:8025"
    
    mariadb:
      image: mariadb:10.4
      container_name: resume-aranda-pablo-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=resume-aranda-pablo
        - MYSQL_USER=demo
        - MYSQL_PASSWORD=demo
      ports:
        - "8085:3306"
        
    webserver:
      image: nginx:alpine
      container_name: resume-aranda-pablo-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/certificates:/etc/ssl/
          - ./docker/certbot/www:/var/www/certbot/
          - ./docker/certbot/conf/:/etc/nginx/ssl/
      ports:
       - "80:80"
    
    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./docker/certbot/www/:/var/www/certbot/
        - ./docker/certbot/conf/:/etc/letsencrypt/

    php-fpm:
      build: docker/php-fpm
      working_dir: /application
      container_name: resume-aranda-pablo-php-fpm8.1
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8084:80
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=resume-aranda-pablo
        - MYSQL_USER=demo
        - MYSQL_PASSWORD=demo
        - PMA_HOST=mariadb